services:
  - type: web
    name: malayalam-voicebot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PORT
        value: 5000
      - key: WS_PORT
        value: 8765
      - key: GOOGLE_APPLICATION_CREDENTIALS
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: BASE_URL
        sync: false
    healthCheckPath: /health